### ISSUE TITLE
Deploy to kubernetes

### ISSUE THREAD

**Issue by ddgenome** [atomist/tslint-automation#2]

**Comment by ddgenome** [comment]
The slow linting, i.e., orders of magnitude slower, seems to be limited to when doing it under the mocha tests.

**Comment by jessitron** [comment]
oh how fascinating. We could choose not to lint test/

**Comment by ddgenome** [comment]
Sorry, I was not clear. Linting the test directory is fine. Running tslint inside a mocha test is orders of magnitude slower than running it normally.

**Comment by ddgenome** [comment]
I've stopped tslint in Cloud Foundry and have it running in our GKE prod cluster. It is sending logs to logzio and stats to datadog.

**Comment by cdupuis** [comment]
Is it linting too?

**Comment by ddgenome** [comment]
It should be, but it is not configured to lint for me.

**Comment by cdupuis** [comment]
Let me see.

**Comment by ddgenome** [comment]
I see logs in logzio and stats in datadog too. Let's see how it behaves over the weekend.

**Comment by ddgenome** [comment]
No restarts on any of the three pods in production since deployment Friday, closing.
