### ISSUE TITLE
spawn separate project for the linting

### ISSUE THREAD

**Issue by jessitron** [atomist/tslint-automation#5]
because it's more likely to stay up. tslint is computationally intensive and node is single-threaded

**Comment by cdupuis** [comment]
I’d not do this. We should use the cluster stuff for this and figure out why it is not staying up with that. We need to understand what is going on before just working around the core issue here.

**Comment by jessitron** [comment]
Rod said tslint is very computationally intensive and that we should spawn for it ... but if you want to look at the clustering and see if we can figure that it too, also interesting.

It does not stay up on PCF or on k8s.

**Comment by ddgenome** [comment]
For various reasons, we're going to keep tslint inside the main processes.
