### ISSUE TITLE
Disable this automation until we can convert it into an SDM

### ISSUE THREAD

**Issue by jessitron** [atomist/tslint-automation#9]
Currently, this functionality is duplicated (not quite as elaborately, but it's less off) via sample-sdm, so we should disable this one rather than fix it.

Target architecture: tslint-automation can be an SDM which implements an autofix goal. or be in the same SDM. I'd like to port the better error formatting (and fixing options) from here to there, and use it for all review comments.

**Comment by ddgenome** [comment]
This has beej disabled
